name: "Release to GitHub"

on:
  push:
    # Create releases only on tags
    tags:
      - "*"

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.5
        id: go

      - name: Release binaries
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
